[versions]

minecraft = "1.21.10"
parchment = "2025.09.14"
fabric-api = "0.138.3+1.21.10"

[libraries]

minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
parchment = { module = "org.parchmentmc.data:parchment-1.21.8", version.ref = "parchment" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
