[versions]

fabric-loader = "0.18.3"
fabric-language-kotlin = "1.13.6+kotlin.2.2.20"

skyblockapi = "4.0.1"
repo-lib = "3.0.2"
devauth = "1.2.1"
hypixelapi = "1.0.1+build.1+mc1.21"

gson = "2.12.1"
guava = "33.5.0-jre"

meowdding-resources = "1.0.15"

ksp = "2.2.10-2.0.2"
meowdding-ktmodules = "1.0.5"
meowdding-ktcodecs = "1.1.8"

loom = "1.14-SNAPSHOT"
kotlin = "2.2.20"

[libraries]

fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

skyblockapi = { module = "tech.thatgravyboat:skyblock-api", version.ref = "skyblockapi" }
hypixelapi = { module = "maven.modrinth:hypixel-mod-api", version.ref = "hypixelapi" }
repo-lib = { module = "tech.thatgravyboat.repo-lib:repo-lib", version.ref = "repo-lib" }
devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }

meowdding-resources = { module = "me.owdding.repo:compacting-resources", version.ref = "meowdding-resources" }
meowdding-ktmodules = { module = "me.owdding.ktmodules:KtModules", version.ref = "meowdding-ktmodules" }
meowdding-ktcodecs = { module = "me.owdding.ktcodecs:KtCodecs", version.ref = "meowdding-ktcodecs" }

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }